// <auto-generated />
namespace FactWeb.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class OrgDocumentLibrary112316 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OrgDocumentLibrary112316));
        
        string IMigrationMetadata.Id
        {
            get { return "201611231600087_OrgDocumentLibrary 11-23-16"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
