// <auto-generated />
namespace FactWeb.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _07282016RFIDueDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_07282016RFIDueDate));
        
        string IMigrationMetadata.Id
        {
            get { return "201607280732421_07-28-2016-RFIDueDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
