// <auto-generated />
namespace FactWeb.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _07282016documenttype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_07282016documenttype));
        
        string IMigrationMetadata.Id
        {
            get { return "201607281333113_07-28-2016-documenttype"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
