// <auto-generated />
namespace FactWeb.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _19042016site_scope_463 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_19042016site_scope_463));
        
        string IMigrationMetadata.Id
        {
            get { return "201604191217543_19-04-2016-site_scope_463"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
