// <auto-generated />
namespace FactWeb.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _09052016IsArchive : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_09052016IsArchive));
        
        string IMigrationMetadata.Id
        {
            get { return "201609051111391_09-05-2016-IsArchive"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
