// <auto-generated />
namespace FactWeb.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _05092016_SiteScopeType_Changes1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_05092016_SiteScopeType_Changes1));
        
        string IMigrationMetadata.Id
        {
            get { return "201605091322509_05-09-2016_SiteScopeType_Changes1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
