// <auto-generated />
namespace FactWeb.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PrimaryUser281116 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PrimaryUser281116));
        
        string IMigrationMetadata.Id
        {
            get { return "201608111942235_PrimaryUser2 8-11-16"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
