// <auto-generated />
namespace FactWeb.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _12142016IsPrimaryAddress : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_12142016IsPrimaryAddress));
        
        string IMigrationMetadata.Id
        {
            get { return "201612141115148_12-14-2016-IsPrimaryAddress"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
