// <auto-generated />
namespace FactWeb.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InspectionScheduleDetailUpdate271916 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InspectionScheduleDetailUpdate271916));
        
        string IMigrationMetadata.Id
        {
            get { return "201607191802467_InspectionScheduleDetail-Update2 7-19-16"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
