// <auto-generated />
namespace FactWeb.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ApplicationVersion2452016 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ApplicationVersion2452016));
        
        string IMigrationMetadata.Id
        {
            get { return "201604051445530_ApplicationVersion2 4-5-2016"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
