// <auto-generated />
namespace FactWeb.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _08312016cycleNumber : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_08312016cycleNumber));
        
        string IMigrationMetadata.Id
        {
            get { return "201608310716562_08-31-2016-cycleNumber"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
