// <auto-generated />
namespace FactWeb.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _03142016_Site_Changes_367 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_03142016_Site_Changes_367));
        
        string IMigrationMetadata.Id
        {
            get { return "201603211221578_03-14-2016_Site_Changes_367"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
