// <auto-generated />
namespace FactWeb.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _18042016_SiteChanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_18042016_SiteChanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201604180933428_18-04-2016_SiteChanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
