// <auto-generated />
namespace FactWeb.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _05112016_UserChanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_05112016_UserChanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201605110910496_05-11-2016_UserChanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
