// <auto-generated />
namespace FactWeb.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _050520161 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_050520161));
        
        string IMigrationMetadata.Id
        {
            get { return "201605051507139_05-05-2016-1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
