// <auto-generated />
namespace FactWeb.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _04_27_2016_UserLock_411 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_04_27_2016_UserLock_411));
        
        string IMigrationMetadata.Id
        {
            get { return "201604271255245_04_27_2016_UserLock_411"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
