// <auto-generated />
namespace FactWeb.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _25042016_Application_Status_470 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_25042016_Application_Status_470));
        
        string IMigrationMetadata.Id
        {
            get { return "201604242145045_25-04-2016_Application_Status_470"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
