// <auto-generated />
namespace FactWeb.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _05052016_511_ApplicationResponse : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_05052016_511_ApplicationResponse));
        
        string IMigrationMetadata.Id
        {
            get { return "201605050920184_05-05-2016_511_ApplicationResponse"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
