// <auto-generated />
namespace FactWeb.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _06212016CommentType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_06212016CommentType));
        
        string IMigrationMetadata.Id
        {
            get { return "201606210949209_06-21-2016-CommentType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
