// <auto-generated />
namespace FactWeb.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DocLibChanges4417 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DocLibChanges4417));
        
        string IMigrationMetadata.Id
        {
            get { return "201704041547144_DocLib Changes 4-4-17"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
