// <auto-generated />
namespace FactWeb.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _01042017MultipleDocuments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_01042017MultipleDocuments));
        
        string IMigrationMetadata.Id
        {
            get { return "201701041255292_01-04-2017-MultipleDocuments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
